---
- name: Docker Compose | Get binary
  shell:
    curl -L https://github.com/docker/compose/releases/download/1.8.0-rc2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    creates=/usr/local/bin/docker-compose

- name: Docker Compose | Change mode
  file: path=/usr/local/bin/docker-compose mode="u+rwx,g+x,o+x"
