---
- name: Docker Daemon | Update cache
  apt: update_cache=yes

- name: docker Daemon | Install extra packages (needed for aufs)
  shell: apt-get install linux-image-extra-$(uname -r)

- name: Docker Daemon | Install certificates
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Docker Daemon | Fetch signing key
  ignore_errors: yes
  command: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070A

- name: Docker Daemon | Add repository
  shell:
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list 
    creates=/etc/apt/sources.list.d/docker.list

- name: Docker Daemon | Purge lxc-docker
  ignore_errors: yes
  apt: name=lxc-docker purge=yes

- name: Docker Daemon | Cache Policy
  ignore_errors: yes
  command: apt-cache policy docker-engine

- name: Docker Daemon | Update cache
  ignore_errors: yes
  apt: update_cache=yes

- name: Docker Daemon | Install daemon
  command: apt-get install -y --force-yes docker-engine
